### ISSUE TITLE
Suggestion "Every Compat" intergration

### ISSUE THREAD

**Issue by knighthawkUnlimited** [Wouink/furnish#14]
Hi, completely understand if it's not doable, but I was wondering if integration with the mod bellow is at all possible. It is supposed to generate variants in all wood types, but I don't know how it would interact with you crafting table :)

https://www.curseforge.com/minecraft/mc-mods/every-compat

**Comment by Wouink** [comment]
Hi, thanks for suggesting! I *might* look into that, but I can't guarantee anything, I have a lot less time these days!
