### ISSUE TITLE
Not loading properly 

### ISSUE THREAD

**Issue by Reecimo** [Wouink/furnish#15]
Doesn't load correctly and constantly gives me an error
[crash-2022-07-26_14.06.04-fml.txt](https://github.com/Wouink/furnish/files/9190020/crash-2022-07-26_14.06.04-fml.txt)
.

**Comment by Wouink** [comment]
Hi, thanks for reporting. It seems to be related to the version of Forge you are using which is older than the version Furnish was updated to. There's nothing I can do to fix that, please udpate to Forge 41.0.107 or later.
