### ISSUE TITLE
[Suggestion] Allow creative players to destroy claimed mailboxes

### ISSUE THREAD

**Issue by Illios42** [Wouink/furnish#16]
Suggestion is in the title, I'd love to see it being implemented or at least a config option to enable this. Reason is that it's very inconvenient for server staff if someone was to spam place and claim mailboxes and you couldn't even destroy them with creative perms. /fill or similar commands become a hassle at a certain point and it's not a perm a lot of staff usually has lmao

Otherwise your mod is really great, keep up the good work!

**Comment by Wouink** [comment]
Hi, thanks for submitting this suggestion! I've added a config option to allow **all** creative players to destroy a claimed Mailbox. By default, only the Mailbox's owner or an operator in creative mode can break a claimed Mailbox.
