### ISSUE TITLE
[BUG] Cant click on Furnish Item in JEI

### ISSUE THREAD

**Issue by SugarDaddii** [Wouink/furnish#17]
When i click on items it doesnt show me how to craft them.
I see in some Videos of you that you click on JEI and it work well and for example you need planks to craft specific furniture!
That doesnt work on my side.

Hava a nice day and very good work with your mod/modelling
<3

**Comment by Wouink** [comment]
Hey, thanks for reporting.
I had to disable that functionality during the port of Furnish to 1.19. It took a while, but JEI support is back in the latest release (Furnish v17 on Curse).

Have a nice day too!
