### ISSUE TITLE
Furnish 18 Chunks disappear

### ISSUE THREAD

**Issue by SugarDaddii** [Wouink/furnish#22]
After Updating your mod a few chunks get removed and dont get render any more

**Comment by Zelioth** [comment]
i found this issue too when updating my mod pack "Friends United" didn't realize it was furnish because I updated a few mods at once. Glad to see you found the problem 

Can also confirm this issue

**Comment by PetiPuss** [comment]
Having the same issue, if you combine any generation mod with furnish it seems to break everything?

**Comment by Wouink** [comment]
Hi,
Thanks for reporting.
Really sorry about that! I had made a mistake in some of Furnish rendering code.
The error was fixed in Furnish v21, which is available for download.
