### ISSUE TITLE
Furnish Verion 18 1.19.2 Dedicated Server Crash on Startup

### ISSUE THREAD

**Issue by Zelioth** [Wouink/furnish#23]
Minecraft 1.19.2
Forge 43.2.4

Crash when launching server on Furnish 18

https://gist.github.com/Zelioth/784d4f0985030d9552c934b643183ab0

**Comment by Wouink** [comment]
Hi,
Thanks for reporting.
It was fixed in newer Furnish releases, sorry for the inconvenience!
