### ISSUE TITLE
[1.18] Why doesn't furnish support EveryCompat (wood good)??????

### ISSUE THREAD

**Issue by Cixon** [Wouink/furnish#24]
Hello! My name is Cixon and I have a few things, I wanted to say before I send my request.
I'm working on a very [ambitious mod-pack](https://www.curseforge.com/minecraft/modpacks/legacy-forge) and I choose furnish as my one and only furniture mod.
The reason for this is simplicity and the designs. I do have one issue.

According to [Every Compat (Wood Good)](https://www.curseforge.com/minecraft/mc-mods/every-compat), they claim you support modded wood types but this isn't present in 1.18.
I'd love if we can make furniture out of modded woods for mods such as twilightforest and [premium wood](https://www.curseforge.com/minecraft/mc-mods/premium-wood) and potentially [biomemakeover](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)!

Now I have already reported this issue over to their curseforge page[ (See Here) ](https://www.curseforge.com/minecraft/mc-mods/every-compat/issues/79)but I figured I'd let you know incase you know these individuals in question and want to add the compat. I'm very happy to see such a mod of theirs exist but I was honestly deepen sadden when your mod Furnish did not have these modded wood types.

PLEASE FIX! THANK YOU!

**Comment by Wouink** [comment]
Hi Cixon!
Thanks for your kind feedback on Furnish! I feel very honored by your choice

In the past (some 1.16 release, I think), I had implemented a hacky system to add furniture sets of a list of woods from Furnish config file. This was very hacky: there was no client/server sync, no recipes and no models/textures/translations added, just the block and it's functionality. This was not a reliable option, but it existed and this is probably why Every Compat mentions Furnish as a compatible mod.

I would love to add support for modded woods to Furnish, but it's not a simple process. It would require data{recipes, tags, loot tables}/models/textures/translations resources for every single block added, which is something I do not have the time to create.

If you find a way to provide all the required resources, maybe I could add the blocks to Furnish code and include your resources. Let me know!

Best regards,
Wouink

**Comment by Cixon** [comment]
> In the past (some 1.16 release, I think), I had implemented a hacky system to add furniture sets of a list of woods from Furnish config file. This was very hacky: there was no client/server sync

This is currently a issue in 1.18.2 as well. I was on my Minecraft server with my girlfriend and noticed the blocks weren't displaying the furniture but instead something oddly different.

> If you find a way to provide all the required resources, maybe I could add the blocks to Furnish code and include your resources. Let me know!

I will honor this request! I don't know exactly how this could be possible but I'm not horrible at photo shop and I think with some time I could do this for you! :-)

**Comment by Cixon** [comment]
I can do this via blockbench or just simply retexturing your pre-existing furniture, whichever you prefer, let me know!
