### ISSUE TITLE
Cannot break blocks after updating.

### ISSUE THREAD

**Issue by nvrsbr** [Wouink/furnish#26]
After updating to the latest version today I can no longer break blocks in my world.
Downgrading to the earlier version fixes it.

FORGE 1.19.2 - **furnish-22-forge.jar**

**Comment by manu1978** [comment]
I confirm that I have the same problem.

**Comment by Wouink** [comment]
Hi, thanks for reporting!
The fix is available for download on Curse.

**Comment by nvrsbr** [comment]
Thanks a ton.

**Comment by nvrsbr** [comment]
Issue is still happening,
