### ISSUE TITLE
Still cannot break blocks with latest version.

### ISSUE THREAD

**Issue by nvrsbr** [Wouink/furnish#28]
Still doing the same thing as before :(

**Comment by manu1978** [comment]
Still the same on the Fabric version too.

**Comment by nvrsbr** [comment]
No idea what happened but its working fine now?
Did you change something?

**Comment by manu1978** [comment]
Yes it works, I deleted it, downloaded it again and no more worries.

**Comment by nvrsbr** [comment]
I had to do the same thing, redownloading it is what fixed it for me.

**Comment by Wouink** [comment]
I didn't change anything. What probably happened is I told you the new version would be available for download, so you downloaded the latest file available at that time, but that was before Curse had approved my updated file, so you downloaded the same file as before: the bugged version. When I told you to verify you were running the latest file, you downloaded the updated file, which had been approved in the mean time, which fixes the bug.

**Comment by nvrsbr** [comment]
NOPE I can confirm that it is the exact same file name I downloaded the first time. It also showed that it was just updated so it had to be the new one. Anyway its fixed so...
