### ISSUE TITLE
Please allow the ability to disable door knocking

### ISSUE THREAD

**Issue by NovaViper** [Wouink/furnish#29]
Hey I've started using this mod on a personal server and the door knocking is very unnerving and loud (especially so with directional sound enabled because it sounds like it's coming right behind me and several others on the server). It sounds like someone is actually knocking on the door in real life. Could there be an configuration option added to make it where it can be disabled? Thanks

**Comment by Wouink** [comment]
Hi,
Furnish v23 addresses this issue.
Door knock can be entirely disabled on server with a datapack (create an empty `#furnish:can_knock_on` block tag).
Clientside, you can enable the Furnish Door Knock Silencer resource pack which is now automatically included in Furnish.
