### ISSUE TITLE
Server crash..again

### ISSUE THREAD

**Issue by littlepianist** [Wouink/furnish#4]
[crash-2022-02-24_00.45.51-server.txt](https://github.com/Wouink/furnish/files/8126193/crash-2022-02-24_00.45.51-server.txt)

**Comment by Wouink** [comment]
Hi, it should be fixed in `1.16.5-0.5-fix1`, which will soon be on CurseForge.
Please note that when submitting an issue, it's a good practice to include some context (Minecraft version, mod version, what context caused the issue).
