### ISSUE TITLE
[suggestion] Disable cycle paintings feature

### ISSUE THREAD

**Issue by pewblaze** [Wouink/furnish#42]
Hi, really love the mod!

Would it be possible to disable the cycle function in a config/gamerule? Im using this mod & the whole point of it vanishes with the cycle feature ^^"

https://modrinth.com/mod/invariable-paintings

**Comment by Wouink** [comment]
Hi, that's a good suggestion, thanks!
It will be available in Furnish v26, which I do not know the release date yet.
