### ISSUE TITLE
Failed to create screen for menu type: furnish:furniture_workbench

### ISSUE THREAD

**Issue by amyfromearth** [Wouink/furnish#43]
On 1.20.1 Quilt you can't use the furniture workbench at all. I've tried with my full modpack and a clean instance with only Furnish, Architectury, and Quilted Fabric API. 

[22:07:09] [Render thread/WARN]: Failed to create screen for menu type: furnish:furniture_workbench
https://mclo.gs/oyUl6yA

**Comment by Wouink** [comment]
Hi, thanks for reporting!
This will be fixed in Furnish v26, which should release soon (in the next week or so).
