### ISSUE TITLE
Stone Brick Chimney requires incorrect material

### ISSUE THREAD

**Issue by burghenby** [Wouink/furnish#47]
Hello! While working on some building I noticed that the Stone Brick Chimney requires blackstone instead of stone bricks.

![image](https://github.com/Wouink/furnish/assets/158222215/de93617d-bb62-4220-99bc-c9008eca60ff)

I'm content to correct this with my own datapack on my version (1.19.2), but I noticed that the recipe is also incorrect in newer versions (1.20 below) so I figured I'd mention it.

![image](https://github.com/Wouink/furnish/assets/158222215/7d37df65-978b-46d7-85af-e39c3ee611ab)

**Mod Version**: 23
**Minecraft Version**: 1.19.2
**Forge Version**: 43.3.5

Thank you for the great mod!

**Comment by Wouink** [comment]
Hi, thanks for reporting!
This will be fixed in Furnish v27.
