### ISSUE TITLE
Suggestion: Mail Delivery system?

### ISSUE THREAD

**Issue by VirtualGaming1** [Wouink/furnish#7]
So I wound if you can make a delivery system for the mail box so players don't have to go to other players mailbox if they are like say 1k blocks away. A balance way of doing this could be delivery time between sending location to receive location.

**Comment by Wouink** [comment]
Hi, it may be a good idea, but I do not think it's feaseable: somehow, Furnish would have to keep track of every mailbox of every player. That may cause lags and possibly a lot of bugs... However, on a multiplayer server I guess one could become the mailman... :)

**Comment by VirtualGaming1** [comment]
then another thing then

>However, on a multiplayer server I guess one could become the mailman...

then how about make a thing to the letter where a mail man can not look unless it is the sender or receiver and same thing for mailbox where he can put the letter in the mailbox it have to be the sender or the receiver. The thing is when I said Receiver for mailbox is if he can not find or the player have not been on the server yet. and have a little text say "Player1 to Player2"
