### ISSUE TITLE
Mailbox Issues

### ISSUE THREAD

**Issue by cvelde** [Wouink/furnish#9]
On a Server using the most recent version: furnish-1.16.5-0.5-fix1

All Clients near a mailbox seem to be crashing when trying to insert a letter, the server also throws an error but remains functional.
This occurs both in creative and survival mode and the only way to recover from this is deleting the mailbox using a level editor.

Also in furnish-1.16.5-0.5-fix1 I seem to be unable to open a mailbox at all, and the nametag doesn't render, which both works fine in 0.5 (I have tested this in a seperate instance with nothing but the furnish mod on the latest forge version and the results are the same, the errors thrown are the same as in the attached server log)

[crash-2022-04-15_19.49.44-client.txt](https://github.com/Wouink/furnish/files/8497316/crash-2022-04-15_19.49.44-client.txt)
[server_error.txt](https://github.com/Wouink/furnish/files/8497352/server_error.txt)

**Comment by Wouink** [comment]
Hi, sorry to hear that. These problems should be fixed in the newer Furnish versions (1.18+), but I won't have the time to backport the changes to 1.16.
